# Generated by Django 3.2 on 2021-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOtpAuthenticationSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.DecimalField(decimal_places=0, default=True, max_digits=5)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('Otp', models.DecimalField(decimal_places=0, default=True, max_digits=10)),
                ('Otp_Created_Count', models.DecimalField(decimal_places=0, default=True, max_digits=4)),
                ('Expire_Time', models.CharField(default=False, max_length=100)),
                ('Firstdate_at', models.DateTimeField(auto_now_add=True)),
                ('Lastdate_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountDetail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile', models.DecimalField(decimal_places=0, default=False, max_digits=12)),
                ('password', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_actived', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
