# Generated by Django 3.2 on 2021-05-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotpauthenticationsystem',
            name='Expire_Time',
            field=models.DateTimeField(),
        ),
    ]
