# Generated by Django 3.2 on 2021-05-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_emailotpauthenticationsystem_expire_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOtpAuthenticationSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.DecimalField(decimal_places=0, default=True, max_digits=5)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('Otp', models.DecimalField(decimal_places=0, default=True, max_digits=10)),
                ('Otp_Created_Count', models.DecimalField(decimal_places=0, default=True, max_digits=4)),
                ('Expire_Time', models.CharField(default=False, max_length=100)),
                ('Firstdate_at', models.DateTimeField(auto_now_add=True)),
                ('Lastdate_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
